# Generated by Django 3.2 on 2021-04-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='photo',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
