# Generated by Django 3.2 on 2021-04-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_alter_tweet_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='photo',
            field=models.URLField(blank=True, max_length=512),
        ),
    ]
