# Generated by Django 3.2 on 2021-04-23 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_followerfollows_follow_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followerfollows',
            old_name='follow_date',
            new_name='followed',
        ),
    ]
