# Generated by Django 3.2 on 2021-04-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_auto_20210423_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followerfollows',
            name='followed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
